In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3, 4]

In [3]:
type(mylist)

list

In [4]:
myarray = np.array(mylist)

In [5]:
myarray

array([1, 2, 3, 4])

In [6]:
my_matrix = [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
matrix_array = np.array(my_matrix)

In [7]:
matrix_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [9]:
np.arange(1, 100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.arange(1, 100, 20)

array([ 1, 21, 41, 61, 81])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [14]:
np.linspace(10, 10, 3)

array([10., 10., 10.])

In [15]:
np.random.rand(2, 5)

array([[0.98928171, 0.33195603, 0.58294283, 0.8123676 , 0.49516545],
       [0.67797642, 0.8171933 , 0.10069943, 0.53523299, 0.30186432]])

In [18]:
np.random.randn(1,5)

array([[-1.08111945, -0.63515725, -0.3807807 , -0.1744826 ,  0.15452082]])

In [19]:
np.random.randint(0, 100, (4, 5))

array([[ 1, 67, 53, 90, 39],
       [ 1, 26, 34,  0,  6],
       [68, 11, 98, 21, 99],
       [78, 14, 12, 36, 61]])

In [20]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [22]:
arr = np.arange(0,25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr = np.random.randint(0, 101, 10)

In [26]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [27]:
ranarr.max()

99

In [28]:
ranarr.min()

2

In [31]:
ranarr.argmin()

7

In [32]:
ranarr.dtype

dtype('int64')

In [33]:
ranarr.shape

(10,)